---
development:
  cloud_name: tremidus
  api_key: '236571757665743'
  api_secret: KzPBjVMkhqwwcIiVvpVZz284YPs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: tremidus
  api_key: '236571757665743'
  api_secret: KzPBjVMkhqwwcIiVvpVZz284YPs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: tremidus
  api_key: '236571757665743'
  api_secret: KzPBjVMkhqwwcIiVvpVZz284YPs
  enhance_image_tag: true
  static_image_support: false
