test: &default

  # Credentials for REST APIs
  client_id: AQP8FqypCXZ9twJ-nTReMmXIba6sotB8OtzeE_uTV8iZXIplSylouRAI4facuyW4jQXvj4wNrjjE9mME
  client_secret: EKQNY2ZYRGQxiLSm0XrdWbYO05x6nU1LJkb9jWUUTJ1zgRVw8B5tYnXnC33KHOrHyU1HxYQyv9t58GI2

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: caleb.ejakait-facilitator_api1.gmail.com
  # password: GVJNC6WB8LSKDSCC
  # signature: A9VVhCVTBKcL7NNLmV9nmY3EgBSUA7udZG8wTr028Fab6DaxoUQM5Ag1
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: caleb.ejakait-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
