# AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
# Title.create!(name:'Mr')
# Title.create!(name:'Ms')
# Title.create!(name:'Mrs')
# Category.create!(name:'Horror')
Category.create!(name:'Fiction', description:"1")
Category.create!(name: 'Classic', description:"1")
Category.create!(name: 'Poetry', description:"1")
Category.create!(name: 'Auto Biographies', description:"1")
Category.create!(name: 'Biographies', description:"1")
Category.create!(name: 'Cook Books', description:"1")
Category.create!(name: 'Technology', description:"1")
Category.create!(name: 'Psychology', description:"1")
Category.create!(name: 'Medicine', description:"1")
Category.create!(name: 'Engineering', description:"1")
Category.create!(name: 'Programming', description:"1")
Category.create!(name: 'Psychiatry', description:"1")
Category.create!(name: 'Motivational', description:"1")
Category.create!(name: 'Politics', description:"1")
